#debug: true
spring:
  application:
    name: 02-grpc-client

  grpc:
    client:
      channels:
        local:
#          health:
#            enabled: true
#            service-name: "Sample" #    サーバーの問題であり・・・
#            service-name: "db"
          address: "static://localhost:9003"
          negotiation-type: plaintext

server:
  port: 8002
#  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
