
spring:
  application:
    name: 03-grpc-server

  grpc:
    server:
      port: 9003
      reflection:
        enabled: true
      health:
        actuator:
          health-indicator-paths:
            - db

  datasource:
    #    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    #    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE;MODE=DB2
    username: sa
    password:
    initialize: true
  sql:
    init:
      platform: h2
  #      schema-locations:
  #      data-locations:
  h2:
    console:
      # enable access from http://localhost:8080/h2-console
      enabled: true

#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123456
#    sqlScriptEncoding: UTF-8
#    driverClassName: org.postgresql.Driver

server:
  port: 8003

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
