

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'


dependencies {

	implementation project(":01-grpc-core")

	implementation "org.springframework.grpc:spring-grpc-client-spring-boot-starter"

	implementation "org.springframework.boot:spring-boot-starter-webmvc"

	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'


	runtimeOnly "com.h2database:h2"
}
